### PR TITLE
Add syntheaToV09 mapper and CLI mapping utility

### PR DESCRIPTION
**Pull request by dehall**
Adds an initial mapping to support converting FHIR patients generated by Synthea to mCODE v0.9.0. This mapping is intended to support only the codes that Synthea uses, not all codes in the various value sets that mCODE defines. 

Also adds a CLI to allow for using these mappers on patient records without having to install it into another application.

Sample breast cancer patient converted using the new syntheaToV09 mapper and CLI:
[sample.json.txt](https://github.com/standardhealth/fhir-mapper/files/3461413/sample.json.txt)

Notes:
 -  The mapper does not convert `MedicationOrder` / `MedicationRequest` to `MedicationStatement` ... MedicationRequest is part of the SHR models but not one of the primary mCODE profiles, whereas MedicationStatement is.
 - The mapper is expected to evolve as the mCODE 0.9 data model gets fully integrated into Flux. I'm open to discussion on how we want to handle that.
 - The mapper was only actually tested on FHIR DSTU2 patients, but since it only ever looks at `Resource.code.coding` which is generally consistent across FHIR versions I expect it to work on STU3/R4 as well as currently written.

### CODE REVIEW

**Comment by mgramigna** [comment]
This looks solid. I just glanced through because we can't really test its actual integration into Flux Notes yet. Two small nit picks that I have:

* Want to just add syntheaToV09 in the list of currently supported mappers in the README?
* Could we add a script to `package.json` called "map" or something whose command is just `node src/cli.js`? That way we can call `yarn map` instead of `node src/cli.js` since the `package.json` script is a little more expressive.

**Comment by dehall** [comment]
I'm going to rebase this to get in the latest changes with fhirpath variables and bundle context. Stay tuned

**Comment by dehall** [comment]
@mgramigna @rdingwell Rebased with the latest and added a few extra things to the syntheaToV09 mapper. This can be tested on the `mcode_09` branch of FluxNotes with the /smartcompass endpoint. Patient Janet238 Waelchi213 on moonshot-dev exercises just about all of the various mappers.

**Comment by Dtphelan1** [comment]
I'm good with this. @dehall spent a fair amount of time explaining what's happening behind the scenes, and I can successfully load adata for 05, 09 and non-mcode patients on launchCompass using this version of the mapper. Great work.

**Pull request merged**
