### PR TITLE
Fhirpath variable support & more

### PR DESCRIPTION
**Pull request by rdingwell**
This PR contains a number of small additions that each could have been included in their own small PR's, but I didn't have time for that seeing how all of the other branches would just build on branches that were not merged into master when being created causing a PR management nightmare.  Modifications are listed below. 

Set up testing and migrating tests from proxy shim.  

Added support for compiling context variables into fhirpath expressions (useful with valueset matching).  The context in this case is a hash of values that can then be used in fhirpath expressions using the % to denote that they are variable expressions.  For example: 

`'Condition.code.coding.code in %codes.first()'` 

This expression will match the codes in the Condition code to the codes variable that was passed in as part of the context when creating the mappers and filters.  

Added support for a context object to be passed into the execution for mappers.  This is different than fhirpath context variables. fhirpath context variables are compiled into the expressions when the mapper is created, there is no way to update these for execution.  The execution context is to allow for something along the lines of a patient everything type bundle to be passed in so the mappers could perform more advanced mapping and filtering based off of the overall patient record and not just a single resource. 

Added configuration to build node and web based distributions.  The node distribution is not designed to work in a browser setting as it assumes that there is a `global` variable available.  Additionally, a dependency has a requirement on the `fs` library , which is not supported on the browser.  This adds an additional configuration to export 2 builds, one targeted at node and the other at browsers

### CODE REVIEW

**Comment by dehall** [comment]
I'm having a little trouble following this -- I think the use of the single term `context` in multiple places is confusing me since it feels like it should be 2 different things. There's the "definition context" which only affects FHIRPath expressions, and then there's the "execution context" which we intend to be the full set of resources in which the current resource being mapped is one. 

Is there a realistic scenario in which the same object would be used in both of these places? If not could you rename some of the variables so there is more distinction between what is what? For example I think `context` in the execution sense is safe to rename to `bundle`. It's less generic obviously but it conveys what we actually intend to do with it. (And also it avoids confusing with `context` on some resources in FHIR which is usually a reference to an Encounter or EpisodeOfCare)

**Comment by rdingwell** [comment]
@dehall name changed

**Comment by mgramigna** [comment]
I can't get the `syntheaToV05` mapper to work in Flux Notes anymore with this branch. I believe this has to do with how the file structure was changed? In Flux Notes, we do `import mappers from 'fhir-mapper';`, but now it looks like it should be `import { mappers } from 'fhir-mapper';` based on the way you changed things? Maybe just a one line companion PR into Flux along with this could suffice.

**Comment by dehall** [comment]
FluxNotes depends on version "^1.0.6" so I think we should be good there until manually updated. Any concerns with releasing a new version (v1.1?) here once this and the syntheaToV09 mapper are done and then bump that in the Flux mCODE 09 branch?

**Comment by rdingwell** [comment]
Agree with @dehall I think in general any updates to this library should be considered independent of flux.   Flux or other users can updated as needed

**Comment by dehall** [comment]
Quick update: requiring version ^1.0.6 means that any minor or patch versions with major version 1 are allowed. Semantic versioning says that a new major version number should be used for changes that break backwards compatibility, so we'll want to tag the new version v2.0.0.

**Comment by mgramigna** [comment]
Yep I agree with above

**Comment by rdingwell** [comment]
@dehall version number has been updated in the package.json file

**Pull request merged**
